[tool.poetry]
name = "chatbot"
version = "0.0.1"
description = "A chatbot that answers questions based on your profile"
authors = []


[tool.poetry.dependencies]
python = "^3.11"
google-generativeai = "0.7"
langchain-google-genai = "^2.0.0"
streamlit = "^1.40.1"
